name: Lint Black

on:
  # Trigger the workflow on push or pull request,
  # but only for the main and develop branches
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
